name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: install can-npm-publish and dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate release note
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
